breakfast  ::= protein "with" breakfast "on the side"
<breakfast> ::= <protein> | <bread> | <protein> "with" <breakfast> "on the side" ;
<protein> ::= <crispiness> "crispy" "bacon" | "sausage" | <cooked> "eggs" ;
<crispiness> ::= "really" | "really" <crispiness> ;
<cooked> ::= "scrambled" | "poached" | "fried" ;
<bread> ::= "toast" | "biscuits" | "English muffin" ;
